// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              26.06-release
// source: plugins/interface_input.api.json

// Package interface_input contains generated bindings for API file interface_input.api.
//
// Contents:
// -  2 messages
package interface_input

import (
	api "go.fd.io/govpp/api"
	interface_types "go.fd.io/govpp/binapi/interface_types"
	_ "go.fd.io/govpp/binapi/ip_types"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "interface_input"
	APIVersion = "0.0.1"
	VersionCrc = 0x685eb5e0
)

// SfdpInterfaceInputSet defines message 'sfdp_interface_input_set'.
type SfdpInterfaceInputSet struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	TenantID  uint32                         `binapi:"u32,name=tenant_id" json:"tenant_id,omitempty"`
	IsIP6     uint8                          `binapi:"u8,name=is_ip6,default=0" json:"is_ip6,omitempty"`
	IsDisable uint8                          `binapi:"u8,name=is_disable" json:"is_disable,omitempty"`
}

func (m *SfdpInterfaceInputSet) Reset()               { *m = SfdpInterfaceInputSet{} }
func (*SfdpInterfaceInputSet) GetMessageName() string { return "sfdp_interface_input_set" }
func (*SfdpInterfaceInputSet) GetCrcString() string   { return "c80a0902" }
func (*SfdpInterfaceInputSet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SfdpInterfaceInputSet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.SwIfIndex
	size += 4 // m.TenantID
	size += 1 // m.IsIP6
	size += 1 // m.IsDisable
	return size
}
func (m *SfdpInterfaceInputSet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeUint32(m.TenantID)
	buf.EncodeUint8(m.IsIP6)
	buf.EncodeUint8(m.IsDisable)
	return buf.Bytes(), nil
}
func (m *SfdpInterfaceInputSet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = interface_types.InterfaceIndex(buf.DecodeUint32())
	m.TenantID = buf.DecodeUint32()
	m.IsIP6 = buf.DecodeUint8()
	m.IsDisable = buf.DecodeUint8()
	return nil
}

// SfdpInterfaceInputSetReply defines message 'sfdp_interface_input_set_reply'.
type SfdpInterfaceInputSetReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *SfdpInterfaceInputSetReply) Reset()               { *m = SfdpInterfaceInputSetReply{} }
func (*SfdpInterfaceInputSetReply) GetMessageName() string { return "sfdp_interface_input_set_reply" }
func (*SfdpInterfaceInputSetReply) GetCrcString() string   { return "e8d4e804" }
func (*SfdpInterfaceInputSetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SfdpInterfaceInputSetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *SfdpInterfaceInputSetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *SfdpInterfaceInputSetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

func init() { file_interface_input_binapi_init() }
func file_interface_input_binapi_init() {
	api.RegisterMessage((*SfdpInterfaceInputSet)(nil), "sfdp_interface_input_set_c80a0902")
	api.RegisterMessage((*SfdpInterfaceInputSetReply)(nil), "sfdp_interface_input_set_reply_e8d4e804")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*SfdpInterfaceInputSet)(nil),
		(*SfdpInterfaceInputSetReply)(nil),
	}
}
