// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/plugins/dhcp6_pd_client_cp.api.json

package dhcp6_pd_client_cp

const (
	APIFile    = "dhcp6_pd_client_cp"
	APIVersion = "2.0.0"
	VersionCrc = 0xd4418668
)
