# Configuration of golangci-lint
#
# see docs: https://golangci-lint.run/usage/configuration/

---
version: "2"

run:
  timeout: 5m

issues:
  exclude-dirs:
    - adapter/mock
  exclude-files:
    - ".*\\.ba.\\.go$"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
