dist: xenial
services: docker

language: go
go:
  - "1.13.x"

go_import_path: git.fd.io/govpp.git

env:
  global:
    - GO_BUILD_TAGS=novpp

before_script:
  - export VPP_IMG="ligato/vpp-base:latest"
  - docker pull $VPP_IMG
  - go mod download

script:
  - make lint || true
  - make test
  - make build
  - make gen-binapi-docker

notifications:
  slack:
    rooms:
      - ligato:QNOK2VgHH6k40T8nQxmSgRmo
    on_success: change
    on_failure: always
