// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/core/interface.api.json

package interfaces

const (
	APIFile    = "interface"
	APIVersion = "3.2.2"
	VersionCrc = 0x29a0076c
)
