// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/core/flow.api.json

package flow

const (
	APIFile    = "flow"
	APIVersion = "0.0.2"
	VersionCrc = 0x140d3585
)
