// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/plugins/tracedump.api.json

package tracedump

const (
	APIFile    = "tracedump"
	APIVersion = "0.1.0"
	VersionCrc = 0x691543d5
)
