// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/plugins/nat64.api.json

package nat64

const (
	APIFile    = "nat64"
	APIVersion = "1.0.0"
	VersionCrc = 0xfbd06e33
)
