// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              20.01
// source: .vppapi/plugins/lacp.api.json

// Package lacp contains generated bindings for API file lacp.api.
//
// Contents:
//   2 aliases
//   6 enums
//   2 messages
//
package lacp

import (
	"net"
	"strconv"

	api "git.fd.io/govpp.git/api"
	codec "git.fd.io/govpp.git/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "lacp"
	APIVersion = "2.0.0"
	VersionCrc = 0x930086a4
)

// IfStatusFlags defines enum 'if_status_flags'.
type IfStatusFlags uint32

const (
	IF_STATUS_API_FLAG_ADMIN_UP IfStatusFlags = 1
	IF_STATUS_API_FLAG_LINK_UP  IfStatusFlags = 2
)

var (
	IfStatusFlags_name = map[uint32]string{
		1: "IF_STATUS_API_FLAG_ADMIN_UP",
		2: "IF_STATUS_API_FLAG_LINK_UP",
	}
	IfStatusFlags_value = map[string]uint32{
		"IF_STATUS_API_FLAG_ADMIN_UP": 1,
		"IF_STATUS_API_FLAG_LINK_UP":  2,
	}
)

func (x IfStatusFlags) String() string {
	s, ok := IfStatusFlags_name[uint32(x)]
	if ok {
		return s
	}
	str := func(n uint32) string {
		s, ok := IfStatusFlags_name[uint32(n)]
		if ok {
			return s
		}
		return "IfStatusFlags(" + strconv.Itoa(int(n)) + ")"
	}
	for i := uint32(0); i <= 32; i++ {
		val := uint32(x)
		if val&(1<<i) != 0 {
			if s != "" {
				s += "|"
			}
			s += str(1 << i)
		}
	}
	if s == "" {
		return str(uint32(x))
	}
	return s
}

// IfType defines enum 'if_type'.
type IfType uint32

const (
	IF_API_TYPE_HARDWARE IfType = 1
	IF_API_TYPE_SUB      IfType = 2
	IF_API_TYPE_P2P      IfType = 3
	IF_API_TYPE_PIPE     IfType = 4
)

var (
	IfType_name = map[uint32]string{
		1: "IF_API_TYPE_HARDWARE",
		2: "IF_API_TYPE_SUB",
		3: "IF_API_TYPE_P2P",
		4: "IF_API_TYPE_PIPE",
	}
	IfType_value = map[string]uint32{
		"IF_API_TYPE_HARDWARE": 1,
		"IF_API_TYPE_SUB":      2,
		"IF_API_TYPE_P2P":      3,
		"IF_API_TYPE_PIPE":     4,
	}
)

func (x IfType) String() string {
	s, ok := IfType_name[uint32(x)]
	if ok {
		return s
	}
	return "IfType(" + strconv.Itoa(int(x)) + ")"
}

// LinkDuplex defines enum 'link_duplex'.
type LinkDuplex uint32

const (
	LINK_DUPLEX_API_UNKNOWN LinkDuplex = 0
	LINK_DUPLEX_API_HALF    LinkDuplex = 1
	LINK_DUPLEX_API_FULL    LinkDuplex = 2
)

var (
	LinkDuplex_name = map[uint32]string{
		0: "LINK_DUPLEX_API_UNKNOWN",
		1: "LINK_DUPLEX_API_HALF",
		2: "LINK_DUPLEX_API_FULL",
	}
	LinkDuplex_value = map[string]uint32{
		"LINK_DUPLEX_API_UNKNOWN": 0,
		"LINK_DUPLEX_API_HALF":    1,
		"LINK_DUPLEX_API_FULL":    2,
	}
)

func (x LinkDuplex) String() string {
	s, ok := LinkDuplex_name[uint32(x)]
	if ok {
		return s
	}
	return "LinkDuplex(" + strconv.Itoa(int(x)) + ")"
}

// MtuProto defines enum 'mtu_proto'.
type MtuProto uint32

const (
	MTU_PROTO_API_L3   MtuProto = 1
	MTU_PROTO_API_IP4  MtuProto = 2
	MTU_PROTO_API_IP6  MtuProto = 3
	MTU_PROTO_API_MPLS MtuProto = 4
	MTU_PROTO_API_N    MtuProto = 5
)

var (
	MtuProto_name = map[uint32]string{
		1: "MTU_PROTO_API_L3",
		2: "MTU_PROTO_API_IP4",
		3: "MTU_PROTO_API_IP6",
		4: "MTU_PROTO_API_MPLS",
		5: "MTU_PROTO_API_N",
	}
	MtuProto_value = map[string]uint32{
		"MTU_PROTO_API_L3":   1,
		"MTU_PROTO_API_IP4":  2,
		"MTU_PROTO_API_IP6":  3,
		"MTU_PROTO_API_MPLS": 4,
		"MTU_PROTO_API_N":    5,
	}
)

func (x MtuProto) String() string {
	s, ok := MtuProto_name[uint32(x)]
	if ok {
		return s
	}
	return "MtuProto(" + strconv.Itoa(int(x)) + ")"
}

// RxMode defines enum 'rx_mode'.
type RxMode uint32

const (
	RX_MODE_API_UNKNOWN   RxMode = 0
	RX_MODE_API_POLLING   RxMode = 1
	RX_MODE_API_INTERRUPT RxMode = 2
	RX_MODE_API_ADAPTIVE  RxMode = 3
	RX_MODE_API_DEFAULT   RxMode = 4
)

var (
	RxMode_name = map[uint32]string{
		0: "RX_MODE_API_UNKNOWN",
		1: "RX_MODE_API_POLLING",
		2: "RX_MODE_API_INTERRUPT",
		3: "RX_MODE_API_ADAPTIVE",
		4: "RX_MODE_API_DEFAULT",
	}
	RxMode_value = map[string]uint32{
		"RX_MODE_API_UNKNOWN":   0,
		"RX_MODE_API_POLLING":   1,
		"RX_MODE_API_INTERRUPT": 2,
		"RX_MODE_API_ADAPTIVE":  3,
		"RX_MODE_API_DEFAULT":   4,
	}
)

func (x RxMode) String() string {
	s, ok := RxMode_name[uint32(x)]
	if ok {
		return s
	}
	return "RxMode(" + strconv.Itoa(int(x)) + ")"
}

// SubIfFlags defines enum 'sub_if_flags'.
type SubIfFlags uint32

const (
	SUB_IF_API_FLAG_NO_TAGS           SubIfFlags = 1
	SUB_IF_API_FLAG_ONE_TAG           SubIfFlags = 2
	SUB_IF_API_FLAG_TWO_TAGS          SubIfFlags = 4
	SUB_IF_API_FLAG_DOT1AD            SubIfFlags = 8
	SUB_IF_API_FLAG_EXACT_MATCH       SubIfFlags = 16
	SUB_IF_API_FLAG_DEFAULT           SubIfFlags = 32
	SUB_IF_API_FLAG_OUTER_VLAN_ID_ANY SubIfFlags = 64
	SUB_IF_API_FLAG_INNER_VLAN_ID_ANY SubIfFlags = 128
	SUB_IF_API_FLAG_MASK_VNET         SubIfFlags = 254
	SUB_IF_API_FLAG_DOT1AH            SubIfFlags = 256
)

var (
	SubIfFlags_name = map[uint32]string{
		1:   "SUB_IF_API_FLAG_NO_TAGS",
		2:   "SUB_IF_API_FLAG_ONE_TAG",
		4:   "SUB_IF_API_FLAG_TWO_TAGS",
		8:   "SUB_IF_API_FLAG_DOT1AD",
		16:  "SUB_IF_API_FLAG_EXACT_MATCH",
		32:  "SUB_IF_API_FLAG_DEFAULT",
		64:  "SUB_IF_API_FLAG_OUTER_VLAN_ID_ANY",
		128: "SUB_IF_API_FLAG_INNER_VLAN_ID_ANY",
		254: "SUB_IF_API_FLAG_MASK_VNET",
		256: "SUB_IF_API_FLAG_DOT1AH",
	}
	SubIfFlags_value = map[string]uint32{
		"SUB_IF_API_FLAG_NO_TAGS":           1,
		"SUB_IF_API_FLAG_ONE_TAG":           2,
		"SUB_IF_API_FLAG_TWO_TAGS":          4,
		"SUB_IF_API_FLAG_DOT1AD":            8,
		"SUB_IF_API_FLAG_EXACT_MATCH":       16,
		"SUB_IF_API_FLAG_DEFAULT":           32,
		"SUB_IF_API_FLAG_OUTER_VLAN_ID_ANY": 64,
		"SUB_IF_API_FLAG_INNER_VLAN_ID_ANY": 128,
		"SUB_IF_API_FLAG_MASK_VNET":         254,
		"SUB_IF_API_FLAG_DOT1AH":            256,
	}
)

func (x SubIfFlags) String() string {
	s, ok := SubIfFlags_name[uint32(x)]
	if ok {
		return s
	}
	str := func(n uint32) string {
		s, ok := SubIfFlags_name[uint32(n)]
		if ok {
			return s
		}
		return "SubIfFlags(" + strconv.Itoa(int(n)) + ")"
	}
	for i := uint32(0); i <= 32; i++ {
		val := uint32(x)
		if val&(1<<i) != 0 {
			if s != "" {
				s += "|"
			}
			s += str(1 << i)
		}
	}
	if s == "" {
		return str(uint32(x))
	}
	return s
}

// InterfaceIndex defines alias 'interface_index'.
type InterfaceIndex uint32

// MacAddress defines alias 'mac_address'.
type MacAddress [6]uint8

func ParseMacAddress(s string) (MacAddress, error) {
	var macaddr MacAddress
	mac, err := net.ParseMAC(s)
	if err != nil {
		return macaddr, err
	}
	copy(macaddr[:], mac[:])
	return macaddr, nil
}

func (x MacAddress) ToMAC() net.HardwareAddr {
	return net.HardwareAddr(x[:])
}

func (x MacAddress) String() string {
	return x.ToMAC().String()
}

func (x *MacAddress) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

func (x *MacAddress) UnmarshalText(text []byte) error {
	mac, err := ParseMacAddress(string(text))
	if err != nil {
		return err
	}
	*x = mac
	return nil
}

// SwInterfaceLacpDetails defines message 'sw_interface_lacp_details'.
type SwInterfaceLacpDetails struct {
	SwIfIndex             InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	InterfaceName         string         `binapi:"string[64],name=interface_name" json:"interface_name,omitempty"`
	RxState               uint32         `binapi:"u32,name=rx_state" json:"rx_state,omitempty"`
	TxState               uint32         `binapi:"u32,name=tx_state" json:"tx_state,omitempty"`
	MuxState              uint32         `binapi:"u32,name=mux_state" json:"mux_state,omitempty"`
	PtxState              uint32         `binapi:"u32,name=ptx_state" json:"ptx_state,omitempty"`
	BondInterfaceName     string         `binapi:"string[64],name=bond_interface_name" json:"bond_interface_name,omitempty"`
	ActorSystemPriority   uint16         `binapi:"u16,name=actor_system_priority" json:"actor_system_priority,omitempty"`
	ActorSystem           MacAddress     `binapi:"mac_address,name=actor_system" json:"actor_system,omitempty"`
	ActorKey              uint16         `binapi:"u16,name=actor_key" json:"actor_key,omitempty"`
	ActorPortPriority     uint16         `binapi:"u16,name=actor_port_priority" json:"actor_port_priority,omitempty"`
	ActorPortNumber       uint16         `binapi:"u16,name=actor_port_number" json:"actor_port_number,omitempty"`
	ActorState            uint8          `binapi:"u8,name=actor_state" json:"actor_state,omitempty"`
	PartnerSystemPriority uint16         `binapi:"u16,name=partner_system_priority" json:"partner_system_priority,omitempty"`
	PartnerSystem         MacAddress     `binapi:"mac_address,name=partner_system" json:"partner_system,omitempty"`
	PartnerKey            uint16         `binapi:"u16,name=partner_key" json:"partner_key,omitempty"`
	PartnerPortPriority   uint16         `binapi:"u16,name=partner_port_priority" json:"partner_port_priority,omitempty"`
	PartnerPortNumber     uint16         `binapi:"u16,name=partner_port_number" json:"partner_port_number,omitempty"`
	PartnerState          uint8          `binapi:"u8,name=partner_state" json:"partner_state,omitempty"`
}

func (m *SwInterfaceLacpDetails) Reset()               { *m = SwInterfaceLacpDetails{} }
func (*SwInterfaceLacpDetails) GetMessageName() string { return "sw_interface_lacp_details" }
func (*SwInterfaceLacpDetails) GetCrcString() string   { return "745ae0ba" }
func (*SwInterfaceLacpDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *SwInterfaceLacpDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4     // m.SwIfIndex
	size += 64    // m.InterfaceName
	size += 4     // m.RxState
	size += 4     // m.TxState
	size += 4     // m.MuxState
	size += 4     // m.PtxState
	size += 64    // m.BondInterfaceName
	size += 2     // m.ActorSystemPriority
	size += 1 * 6 // m.ActorSystem
	size += 2     // m.ActorKey
	size += 2     // m.ActorPortPriority
	size += 2     // m.ActorPortNumber
	size += 1     // m.ActorState
	size += 2     // m.PartnerSystemPriority
	size += 1 * 6 // m.PartnerSystem
	size += 2     // m.PartnerKey
	size += 2     // m.PartnerPortPriority
	size += 2     // m.PartnerPortNumber
	size += 1     // m.PartnerState
	return size
}
func (m *SwInterfaceLacpDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(uint32(m.SwIfIndex))
	buf.EncodeString(m.InterfaceName, 64)
	buf.EncodeUint32(m.RxState)
	buf.EncodeUint32(m.TxState)
	buf.EncodeUint32(m.MuxState)
	buf.EncodeUint32(m.PtxState)
	buf.EncodeString(m.BondInterfaceName, 64)
	buf.EncodeUint16(m.ActorSystemPriority)
	buf.EncodeBytes(m.ActorSystem[:], 6)
	buf.EncodeUint16(m.ActorKey)
	buf.EncodeUint16(m.ActorPortPriority)
	buf.EncodeUint16(m.ActorPortNumber)
	buf.EncodeUint8(m.ActorState)
	buf.EncodeUint16(m.PartnerSystemPriority)
	buf.EncodeBytes(m.PartnerSystem[:], 6)
	buf.EncodeUint16(m.PartnerKey)
	buf.EncodeUint16(m.PartnerPortPriority)
	buf.EncodeUint16(m.PartnerPortNumber)
	buf.EncodeUint8(m.PartnerState)
	return buf.Bytes(), nil
}
func (m *SwInterfaceLacpDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.SwIfIndex = InterfaceIndex(buf.DecodeUint32())
	m.InterfaceName = buf.DecodeString(64)
	m.RxState = buf.DecodeUint32()
	m.TxState = buf.DecodeUint32()
	m.MuxState = buf.DecodeUint32()
	m.PtxState = buf.DecodeUint32()
	m.BondInterfaceName = buf.DecodeString(64)
	m.ActorSystemPriority = buf.DecodeUint16()
	copy(m.ActorSystem[:], buf.DecodeBytes(6))
	m.ActorKey = buf.DecodeUint16()
	m.ActorPortPriority = buf.DecodeUint16()
	m.ActorPortNumber = buf.DecodeUint16()
	m.ActorState = buf.DecodeUint8()
	m.PartnerSystemPriority = buf.DecodeUint16()
	copy(m.PartnerSystem[:], buf.DecodeBytes(6))
	m.PartnerKey = buf.DecodeUint16()
	m.PartnerPortPriority = buf.DecodeUint16()
	m.PartnerPortNumber = buf.DecodeUint16()
	m.PartnerState = buf.DecodeUint8()
	return nil
}

// SwInterfaceLacpDump defines message 'sw_interface_lacp_dump'.
type SwInterfaceLacpDump struct{}

func (m *SwInterfaceLacpDump) Reset()               { *m = SwInterfaceLacpDump{} }
func (*SwInterfaceLacpDump) GetMessageName() string { return "sw_interface_lacp_dump" }
func (*SwInterfaceLacpDump) GetCrcString() string   { return "51077d14" }
func (*SwInterfaceLacpDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *SwInterfaceLacpDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *SwInterfaceLacpDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *SwInterfaceLacpDump) Unmarshal(b []byte) error {
	return nil
}

func init() { file_lacp_binapi_init() }
func file_lacp_binapi_init() {
	api.RegisterMessage((*SwInterfaceLacpDetails)(nil), "sw_interface_lacp_details_745ae0ba")
	api.RegisterMessage((*SwInterfaceLacpDump)(nil), "sw_interface_lacp_dump_51077d14")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*SwInterfaceLacpDetails)(nil),
		(*SwInterfaceLacpDump)(nil),
	}
}
