// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.4.0-dev
//  VPP:              20.05-release
// source: /usr/share/vpp/api/core/af_packet.api.json

/*
Package af_packet contains generated code for VPP API file af_packet.api (2.0.0).

It consists of:
	  2 aliases
	  6 enums
	  8 messages
*/
package af_packet

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"net"
	"strconv"
	"strings"

	api "git.fd.io/govpp.git/api"
	codec "git.fd.io/govpp.git/codec"
	struc "github.com/lunixbochs/struc"

	interface_types "git.fd.io/govpp.git/examples/binapi/interface_types"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2 // please upgrade the GoVPP api package

const (
	// ModuleName is the name of this module.
	ModuleName = "af_packet"
	// APIVersion is the API version of this module.
	APIVersion = "2.0.0"
	// VersionCrc is the CRC of this module.
	VersionCrc = 0xe0b6c022
)

// MacAddress represents VPP binary API alias 'mac_address'.
type MacAddress [6]uint8

func ParseMAC(mac string) (parsed MacAddress, err error) {
	var hw net.HardwareAddr
	if hw, err = net.ParseMAC(mac); err != nil {
		return
	}
	copy(parsed[:], hw[:])
	return
}

func (m *MacAddress) ToString() string {
	return net.HardwareAddr(m[:]).String()
}

// AfPacketCreate represents VPP binary API message 'af_packet_create'.
type AfPacketCreate struct {
	HwAddr          MacAddress `binapi:"mac_address,name=hw_addr" json:"hw_addr,omitempty"`
	UseRandomHwAddr bool       `binapi:"bool,name=use_random_hw_addr" json:"use_random_hw_addr,omitempty"`
	HostIfName      string     `binapi:"string[64],name=host_if_name" json:"host_if_name,omitempty" struc:"[64]byte"`
}

func (m *AfPacketCreate) Reset()                        { *m = AfPacketCreate{} }
func (*AfPacketCreate) GetMessageName() string          { return "af_packet_create" }
func (*AfPacketCreate) GetCrcString() string            { return "a190415f" }
func (*AfPacketCreate) GetMessageType() api.MessageType { return api.RequestMessage }

func (m *AfPacketCreate) Size() int {
	if m == nil {
		return 0
	}
	var size int
	// field[1] m.HwAddr
	size += 6
	// field[1] m.UseRandomHwAddr
	size += 1
	// field[1] m.HostIfName
	size += 64
	return size
}
func (m *AfPacketCreate) Marshal(b []byte) ([]byte, error) {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	var buf []byte
	if b == nil {
		buf = make([]byte, m.Size())
	} else {
		buf = b
	}
	// field[1] m.HwAddr
	for i := 0; i < 6; i++ {
		var x uint8
		if i < len(m.HwAddr) {
			x = uint8(m.HwAddr[i])
		}
		buf[pos] = uint8(x)
		pos += 1
	}
	// field[1] m.UseRandomHwAddr
	if m.UseRandomHwAddr {
		buf[pos] = 1
	}
	pos += 1
	// field[1] m.HostIfName
	copy(buf[pos:pos+64], m.HostIfName)
	pos += 64
	return buf, nil
}
func (m *AfPacketCreate) Unmarshal(tmp []byte) error {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	// field[1] m.HwAddr
	for i := 0; i < len(m.HwAddr); i++ {
		m.HwAddr[i] = uint8(tmp[pos])
		pos += 1
	}
	// field[1] m.UseRandomHwAddr
	m.UseRandomHwAddr = tmp[pos] != 0
	pos += 1
	// field[1] m.HostIfName
	{
		nul := bytes.Index(tmp[pos:pos+64], []byte{0x00})
		m.HostIfName = codec.DecodeString(tmp[pos : pos+nul])
		pos += 64
	}
	return nil
}

// AfPacketCreateReply represents VPP binary API message 'af_packet_create_reply'.
type AfPacketCreateReply struct {
	Retval    int32                          `binapi:"i32,name=retval" json:"retval,omitempty"`
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
}

func (m *AfPacketCreateReply) Reset()                        { *m = AfPacketCreateReply{} }
func (*AfPacketCreateReply) GetMessageName() string          { return "af_packet_create_reply" }
func (*AfPacketCreateReply) GetCrcString() string            { return "5383d31f" }
func (*AfPacketCreateReply) GetMessageType() api.MessageType { return api.ReplyMessage }

func (m *AfPacketCreateReply) Size() int {
	if m == nil {
		return 0
	}
	var size int
	// field[1] m.Retval
	size += 4
	// field[1] m.SwIfIndex
	size += 4
	return size
}
func (m *AfPacketCreateReply) Marshal(b []byte) ([]byte, error) {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	var buf []byte
	if b == nil {
		buf = make([]byte, m.Size())
	} else {
		buf = b
	}
	// field[1] m.Retval
	o.PutUint32(buf[pos:pos+4], uint32(m.Retval))
	pos += 4
	// field[1] m.SwIfIndex
	o.PutUint32(buf[pos:pos+4], uint32(m.SwIfIndex))
	pos += 4
	return buf, nil
}
func (m *AfPacketCreateReply) Unmarshal(tmp []byte) error {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	// field[1] m.Retval
	m.Retval = int32(o.Uint32(tmp[pos : pos+4]))
	pos += 4
	// field[1] m.SwIfIndex
	m.SwIfIndex = interface_types.InterfaceIndex(o.Uint32(tmp[pos : pos+4]))
	pos += 4
	return nil
}

// AfPacketDelete represents VPP binary API message 'af_packet_delete'.
type AfPacketDelete struct {
	HostIfName string `binapi:"string[64],name=host_if_name" json:"host_if_name,omitempty" struc:"[64]byte"`
}

func (m *AfPacketDelete) Reset()                        { *m = AfPacketDelete{} }
func (*AfPacketDelete) GetMessageName() string          { return "af_packet_delete" }
func (*AfPacketDelete) GetCrcString() string            { return "863fa648" }
func (*AfPacketDelete) GetMessageType() api.MessageType { return api.RequestMessage }

func (m *AfPacketDelete) Size() int {
	if m == nil {
		return 0
	}
	var size int
	// field[1] m.HostIfName
	size += 64
	return size
}
func (m *AfPacketDelete) Marshal(b []byte) ([]byte, error) {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	var buf []byte
	if b == nil {
		buf = make([]byte, m.Size())
	} else {
		buf = b
	}
	// field[1] m.HostIfName
	copy(buf[pos:pos+64], m.HostIfName)
	pos += 64
	return buf, nil
}
func (m *AfPacketDelete) Unmarshal(tmp []byte) error {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	// field[1] m.HostIfName
	{
		nul := bytes.Index(tmp[pos:pos+64], []byte{0x00})
		m.HostIfName = codec.DecodeString(tmp[pos : pos+nul])
		pos += 64
	}
	return nil
}

// AfPacketDeleteReply represents VPP binary API message 'af_packet_delete_reply'.
type AfPacketDeleteReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AfPacketDeleteReply) Reset()                        { *m = AfPacketDeleteReply{} }
func (*AfPacketDeleteReply) GetMessageName() string          { return "af_packet_delete_reply" }
func (*AfPacketDeleteReply) GetCrcString() string            { return "e8d4e804" }
func (*AfPacketDeleteReply) GetMessageType() api.MessageType { return api.ReplyMessage }

func (m *AfPacketDeleteReply) Size() int {
	if m == nil {
		return 0
	}
	var size int
	// field[1] m.Retval
	size += 4
	return size
}
func (m *AfPacketDeleteReply) Marshal(b []byte) ([]byte, error) {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	var buf []byte
	if b == nil {
		buf = make([]byte, m.Size())
	} else {
		buf = b
	}
	// field[1] m.Retval
	o.PutUint32(buf[pos:pos+4], uint32(m.Retval))
	pos += 4
	return buf, nil
}
func (m *AfPacketDeleteReply) Unmarshal(tmp []byte) error {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	// field[1] m.Retval
	m.Retval = int32(o.Uint32(tmp[pos : pos+4]))
	pos += 4
	return nil
}

// AfPacketDetails represents VPP binary API message 'af_packet_details'.
type AfPacketDetails struct {
	SwIfIndex  interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	HostIfName string                         `binapi:"string[64],name=host_if_name" json:"host_if_name,omitempty" struc:"[64]byte"`
}

func (m *AfPacketDetails) Reset()                        { *m = AfPacketDetails{} }
func (*AfPacketDetails) GetMessageName() string          { return "af_packet_details" }
func (*AfPacketDetails) GetCrcString() string            { return "58c7c042" }
func (*AfPacketDetails) GetMessageType() api.MessageType { return api.ReplyMessage }

func (m *AfPacketDetails) Size() int {
	if m == nil {
		return 0
	}
	var size int
	// field[1] m.SwIfIndex
	size += 4
	// field[1] m.HostIfName
	size += 64
	return size
}
func (m *AfPacketDetails) Marshal(b []byte) ([]byte, error) {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	var buf []byte
	if b == nil {
		buf = make([]byte, m.Size())
	} else {
		buf = b
	}
	// field[1] m.SwIfIndex
	o.PutUint32(buf[pos:pos+4], uint32(m.SwIfIndex))
	pos += 4
	// field[1] m.HostIfName
	copy(buf[pos:pos+64], m.HostIfName)
	pos += 64
	return buf, nil
}
func (m *AfPacketDetails) Unmarshal(tmp []byte) error {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	// field[1] m.SwIfIndex
	m.SwIfIndex = interface_types.InterfaceIndex(o.Uint32(tmp[pos : pos+4]))
	pos += 4
	// field[1] m.HostIfName
	{
		nul := bytes.Index(tmp[pos:pos+64], []byte{0x00})
		m.HostIfName = codec.DecodeString(tmp[pos : pos+nul])
		pos += 64
	}
	return nil
}

// AfPacketDump represents VPP binary API message 'af_packet_dump'.
type AfPacketDump struct{}

func (m *AfPacketDump) Reset()                        { *m = AfPacketDump{} }
func (*AfPacketDump) GetMessageName() string          { return "af_packet_dump" }
func (*AfPacketDump) GetCrcString() string            { return "51077d14" }
func (*AfPacketDump) GetMessageType() api.MessageType { return api.RequestMessage }

func (m *AfPacketDump) Size() int {
	if m == nil {
		return 0
	}
	var size int
	return size
}
func (m *AfPacketDump) Marshal(b []byte) ([]byte, error) {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	var buf []byte
	if b == nil {
		buf = make([]byte, m.Size())
	} else {
		buf = b
	}
	return buf, nil
}
func (m *AfPacketDump) Unmarshal(tmp []byte) error {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	return nil
}

// AfPacketSetL4CksumOffload represents VPP binary API message 'af_packet_set_l4_cksum_offload'.
type AfPacketSetL4CksumOffload struct {
	SwIfIndex interface_types.InterfaceIndex `binapi:"interface_index,name=sw_if_index" json:"sw_if_index,omitempty"`
	Set       bool                           `binapi:"bool,name=set" json:"set,omitempty"`
}

func (m *AfPacketSetL4CksumOffload) Reset()                        { *m = AfPacketSetL4CksumOffload{} }
func (*AfPacketSetL4CksumOffload) GetMessageName() string          { return "af_packet_set_l4_cksum_offload" }
func (*AfPacketSetL4CksumOffload) GetCrcString() string            { return "319cd5c8" }
func (*AfPacketSetL4CksumOffload) GetMessageType() api.MessageType { return api.RequestMessage }

func (m *AfPacketSetL4CksumOffload) Size() int {
	if m == nil {
		return 0
	}
	var size int
	// field[1] m.SwIfIndex
	size += 4
	// field[1] m.Set
	size += 1
	return size
}
func (m *AfPacketSetL4CksumOffload) Marshal(b []byte) ([]byte, error) {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	var buf []byte
	if b == nil {
		buf = make([]byte, m.Size())
	} else {
		buf = b
	}
	// field[1] m.SwIfIndex
	o.PutUint32(buf[pos:pos+4], uint32(m.SwIfIndex))
	pos += 4
	// field[1] m.Set
	if m.Set {
		buf[pos] = 1
	}
	pos += 1
	return buf, nil
}
func (m *AfPacketSetL4CksumOffload) Unmarshal(tmp []byte) error {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	// field[1] m.SwIfIndex
	m.SwIfIndex = interface_types.InterfaceIndex(o.Uint32(tmp[pos : pos+4]))
	pos += 4
	// field[1] m.Set
	m.Set = tmp[pos] != 0
	pos += 1
	return nil
}

// AfPacketSetL4CksumOffloadReply represents VPP binary API message 'af_packet_set_l4_cksum_offload_reply'.
type AfPacketSetL4CksumOffloadReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *AfPacketSetL4CksumOffloadReply) Reset() { *m = AfPacketSetL4CksumOffloadReply{} }
func (*AfPacketSetL4CksumOffloadReply) GetMessageName() string {
	return "af_packet_set_l4_cksum_offload_reply"
}
func (*AfPacketSetL4CksumOffloadReply) GetCrcString() string            { return "e8d4e804" }
func (*AfPacketSetL4CksumOffloadReply) GetMessageType() api.MessageType { return api.ReplyMessage }

func (m *AfPacketSetL4CksumOffloadReply) Size() int {
	if m == nil {
		return 0
	}
	var size int
	// field[1] m.Retval
	size += 4
	return size
}
func (m *AfPacketSetL4CksumOffloadReply) Marshal(b []byte) ([]byte, error) {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	var buf []byte
	if b == nil {
		buf = make([]byte, m.Size())
	} else {
		buf = b
	}
	// field[1] m.Retval
	o.PutUint32(buf[pos:pos+4], uint32(m.Retval))
	pos += 4
	return buf, nil
}
func (m *AfPacketSetL4CksumOffloadReply) Unmarshal(tmp []byte) error {
	o := binary.BigEndian
	_ = o
	pos := 0
	_ = pos
	// field[1] m.Retval
	m.Retval = int32(o.Uint32(tmp[pos : pos+4]))
	pos += 4
	return nil
}

func init() { file_af_packet_binapi_init() }
func file_af_packet_binapi_init() {
	api.RegisterMessage((*AfPacketCreate)(nil), "af_packet.AfPacketCreate")
	api.RegisterMessage((*AfPacketCreateReply)(nil), "af_packet.AfPacketCreateReply")
	api.RegisterMessage((*AfPacketDelete)(nil), "af_packet.AfPacketDelete")
	api.RegisterMessage((*AfPacketDeleteReply)(nil), "af_packet.AfPacketDeleteReply")
	api.RegisterMessage((*AfPacketDetails)(nil), "af_packet.AfPacketDetails")
	api.RegisterMessage((*AfPacketDump)(nil), "af_packet.AfPacketDump")
	api.RegisterMessage((*AfPacketSetL4CksumOffload)(nil), "af_packet.AfPacketSetL4CksumOffload")
	api.RegisterMessage((*AfPacketSetL4CksumOffloadReply)(nil), "af_packet.AfPacketSetL4CksumOffloadReply")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*AfPacketCreate)(nil),
		(*AfPacketCreateReply)(nil),
		(*AfPacketDelete)(nil),
		(*AfPacketDeleteReply)(nil),
		(*AfPacketDetails)(nil),
		(*AfPacketDump)(nil),
		(*AfPacketSetL4CksumOffload)(nil),
		(*AfPacketSetL4CksumOffloadReply)(nil),
	}
}

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = codec.DecodeString
var _ = bytes.NewBuffer
var _ = context.Background
var _ = io.Copy
var _ = strconv.Itoa
var _ = strings.Contains
var _ = struc.Pack
var _ = binary.BigEndian
var _ = math.Float32bits
var _ = net.ParseIP
var _ = fmt.Errorf
