// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/plugins/pppoe.api.json

package pppoe

const (
	APIFile    = "pppoe"
	APIVersion = "2.0.0"
	VersionCrc = 0xec9e86bf
)
