// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/plugins/map.api.json

package maps

const (
	APIFile    = "map"
	APIVersion = "4.2.1"
	VersionCrc = 0xd1f7f56c
)
