// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/core/flow_types.api.json

package flow_types

const (
	APIFile    = "flow_types"
	APIVersion = "0.0.3"
	VersionCrc = 0xd789ede8
)
