// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package pvti

import (
	"context"
	"fmt"
	"io"

	api "go.fd.io/govpp/api"
	memclnt "go.fd.io/govpp/binapi/memclnt"
)

// RPCService defines RPC service pvti.
type RPCService interface {
	PvtiInterfaceCreate(ctx context.Context, in *PvtiInterfaceCreate) (*PvtiInterfaceCreateReply, error)
	PvtiInterfaceDelete(ctx context.Context, in *PvtiInterfaceDelete) (*PvtiInterfaceDeleteReply, error)
	PvtiInterfaceDump(ctx context.Context, in *PvtiInterfaceDump) (RPCService_PvtiInterfaceDumpClient, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) PvtiInterfaceCreate(ctx context.Context, in *PvtiInterfaceCreate) (*PvtiInterfaceCreateReply, error) {
	out := new(PvtiInterfaceCreateReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) PvtiInterfaceDelete(ctx context.Context, in *PvtiInterfaceDelete) (*PvtiInterfaceDeleteReply, error) {
	out := new(PvtiInterfaceDeleteReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) PvtiInterfaceDump(ctx context.Context, in *PvtiInterfaceDump) (RPCService_PvtiInterfaceDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_PvtiInterfaceDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_PvtiInterfaceDumpClient interface {
	Recv() (*PvtiInterfaceDetails, error)
	api.Stream
}

type serviceClient_PvtiInterfaceDumpClient struct {
	api.Stream
}

func (c *serviceClient_PvtiInterfaceDumpClient) Recv() (*PvtiInterfaceDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *PvtiInterfaceDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}
