// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/plugins/trace.api.json

package trace

const (
	APIFile    = "trace"
	APIVersion = "1.0.0"
	VersionCrc = 0x397cbf90
)
