// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.5.0-dev
//  VPP:              21.06-release
// source: /usr/share/vpp/api/plugins/oddbuf.api.json

package oddbuf

const (
	APIFile    = "oddbuf"
	APIVersion = "0.1.0"
	VersionCrc = 0x3a1a2c50
)
